  # Dev container service - runs all services for development
services:
  full-stack-devcontainer:
    container_name: cobi-devcontainer-${TAG}
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.devcontainer
    env_file:
      - ./.env
    restart: no
    depends_on:
      - frontend
      - backend
      - mongodb
      - mongo-express
    command: tail -f /dev/null
    user: app
    volumes:
      - .:/cobi:cached
      - cobi-commandhistory:/var/cobi/commandhistory
      - cobi-vscode-extensions:/home/app/.vscode-server/extensions
      - cobi-vscode-data:/home/app/.vscode-server/data

volumes:
  cobi-commandhistory:
  cobi-vscode-extensions:
  cobi-vscode-data: